---
title: "Clean R225"
format: html
---

```{r}
library(tidyverse)
library(glue)
```

Setup

```{r}
path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "Data",
  .sep = "/"
)
```

Read file

```{r}
data_raw <-
  readxl::read_excel(
    glue("{path_data}/raw/r225.xls"),
    sheet = "By Owner Project Task Sub Task", skip = 8,
    col_types = c(
      rep("text", 3),
      rep("numeric", 1),
      rep("text", 1),
      rep("numeric", 1),
      rep("text", 3),
      rep("numeric", 7)
    )
  ) %>%
  janitor::clean_names()
```

Rename columns

```{r}
data_renamed <-
  data_raw %>%
  select(
    agency_owner = owner_agency,
    project_number = project_no,
    project_name = project_title,
    task_number = task_no,
    task_name = task_name,
    subtask_number = sub_task,
    subtask_name = sub_task_name,
    fund_number = fund_detail,
    fund_name = fund_detail_title,
    authority_ltd = ltd_authority,
    authority_balance = authority_balance,
    allotment_ltd = ltd_allotment,
    allotment_balance = allotment_balance,
    commitments_ltd = ltd_commitments,
    obligations_ltd = ltd_obligations,
    expenditures_ltd = ltd_expenditure
  )
```

Transform columns

```{r}
data_transformed <-
  data_renamed %>%
  mutate(
    across(
      c(
        authority_ltd,
        authority_balance,
        allotment_ltd,
        allotment_balance,
        commitments_ltd,
        obligations_ltd,
        expenditures_ltd
      ),
      \(x) round(x, 2)
    )
  ) %>%
  mutate(
    across(
      c(
        project_name
      ),
      \(x) str_to_upper(x)
    )
  ) %>%
  mutate(fund_name = case_when(
    fund_name == "LONG TERM / G.O. / I.T. BONDS" ~ "Bonds: Long-Term",
    fund_name == "SHORT - TERM BONDS" ~ "Bonds: Short-Term",
    fund_name == "PAY AS YOU GO" ~ "PAYGO: Unrestricted",
    fund_name == "PAYGO-RESTRICTED" ~ "PAYGO: Restricted",
    fund_name == "CAPITAL FUND - PRIVATE CONTRIBUTIONS" ~ "Private",
    fund_name == "INTRA DISTRICT CAPITAL" ~ "Intra-District",
    .default = fund_name
  )) %>%
  filter(agency_owner == "GA0") %>%
  arrange(
    agency_owner, project_number, task_number, subtask_number, fund_number
  )
```

Separate balances and spend into different tables

Balances

```{r}
balances_225 <-
  data_transformed %>%
  select(!c(commitments_ltd, obligations_ltd, expenditures_ltd))

balances_225 %>%
  writexl::write_xlsx(glue("{path_data}/clean/balances_225.xlsx"))
```

Spend

```{r}
spend_225 <-
  data_transformed %>%
  select(
    !c(authority_ltd, authority_balance, allotment_ltd, allotment_balance)
  ) %>%
  pivot_longer(
    cols = c(commitments_ltd, obligations_ltd, expenditures_ltd),
    names_to = "spend_type", values_to = "spend_amount"
  ) %>%
  mutate(spend_type = case_when(
    spend_type == "commitments_ltd" ~ "1. Commitments",
    spend_type == "obligations_ltd" ~ "2. Obligations",
    spend_type == "expenditures_ltd" ~ "3. Expenditures",
  ))

spend_225 %>%
  writexl::write_xlsx(glue("{path_data}/clean/spend_225.xlsx"))
```

```{r}
Sys.time()
```
